-- MySQL Script generated by MySQL Workbench
-- Wed Jun 25 12:15:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema payMyBuddy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema payMyBuddy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `payMyBuddy` DEFAULT CHARACTER SET utf8 ;
USE `payMyBuddy` ;

-- -----------------------------------------------------
-- Table `bank_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_account` (
  `idBankAccount` BIGINT NOT NULL AUTO_INCREMENT,
  `balance` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idBankAccount`),
  UNIQUE INDEX `idBankAccount_UNIQUE` (`idBankAccount` ASC)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `idUser` BINARY(16) NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `idBankAccount` BIGINT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_user_bank_account_idx` (`idBankAccount` ASC),
  CONSTRAINT `fk_user_bank_account`
    FOREIGN KEY (`idBankAccount`)
    REFERENCES `bank_account` (`idBankAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friend` (
  `idUser_1` BINARY(16) NOT NULL,
  `idUser_2` BINARY(16) NOT NULL,
  PRIMARY KEY (`idUser_1`, `idUser_2`),
  INDEX `idUser_2_idx` (`idUser_2` ASC),
  CONSTRAINT `fk_friend_user1`
    FOREIGN KEY (`idUser_1`)
    REFERENCES `user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend_user2`
    FOREIGN KEY (`idUser_2`)
    REFERENCES `user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transaction` (
  `idTransaction` BIGINT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NOT NULL,
  `date` DATETIME NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `idUserSender` BINARY(16) NOT NULL,
  `idUserReceveir` BINARY(16) NOT NULL,
  `fee` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idTransaction`),
  INDEX `idUserSender_idx` (`idUserSender` ASC),
  INDEX `idUserReceveir_idx` (`idUserReceveir` ASC),
  CONSTRAINT `fk_transaction_sender`
    FOREIGN KEY (`idUserSender`)
    REFERENCES `user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_receveir`
    FOREIGN KEY (`idUserReceveir`)
    REFERENCES `user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
